package StandAlone;

import java.io.IOException;
import java.awt.event.*;
import javax.swing.*;
import java.awt.*;
import javax.swing.border.TitledBorder;

/**
 * Write a description of class RegisterGUI here.
 * 
 * @author (your name) 
 * @version (a version number or a date)
 */
public class RegisterGUI extends GUI {

    private JPanel regInput;
    private JTextField username, name, email;
    private JButton submit, back;
    private JPasswordField password, confirm;

    //Connect to the GUI controller.
    public RegisterGUI(GUIControl c) {
        super(c, "Register");
        initialize();
    }

    //Initialize GUI and add GUI components.
    private void initialize() {
        regInput = new JPanel();
        regInput.setLayout(new GridLayout(6,2,20,20));
        regInput.setBorder(new TitledBorder("Please enter below information"));
        regInput.add(new JLabel("Username:"));
        username = new JTextField(8);
        regInput.add(username);
        regInput.add(new JLabel("Password:"));
        password = new JPasswordField(8);
        regInput.add(password);
        regInput.add(new JLabel("Type again password:"));
        confirm = new JPasswordField(8);
        regInput.add(confirm);
        regInput.add(new JLabel("Name:"));
        name = new JTextField(8);
        regInput.add(name);
        regInput.add(new JLabel("Email:"));
        email = new JTextField(8);
        email.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {

            }

            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER)
                    performRegister();
            }

            @Override
            public void keyReleased(KeyEvent e) {

            }
        });
        regInput.add(email);
        back = new JButton("Back");
        regInput.add(back);
        submit = new JButton("Submit");
        regInput.add(submit);
        add(regInput);
        setSize(300,300);
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        back.addActionListener(new Listener());
        submit.addActionListener(new Listener());
    }
    
    //Handle all the events.
    class Listener implements ActionListener {
        public void actionPerformed (ActionEvent e)
        {
            if (e.getSource() == back)
            {
                close();
                control.redirect("Login");
            }
            
            else if (e.getSource() == submit)
            {
                performRegister();
            }
        }
    }

    private void performRegister() {
        String u = username.getText();
        String p1 = String.valueOf(password.getPassword());
        String p2 = String.valueOf(confirm.getPassword());
        String n = name.getText();
        String em = email.getText();

        if (u == null || p1 == null || p2 == null || n == null || em == null ||
            u.isEmpty() || p1.isEmpty() || p2.isEmpty() || n.isEmpty() || em.isEmpty()) {
                JOptionPane.showMessageDialog(new JFrame(), "Please fill in the blank field(s)");
                //Ensure all fields is filled.
            }
            else {
                if (p1.equals(p2)) //Ensure two entered password is the same.
                {
                    control.user = new UserProfile(u, n, em);
                    String command = "register";
                    String profile = control.user.toString();
                    p1 = control.getMD5(p1);
                    String postData = "command=" + command + "&username=" +
                    u + "&password=" + p1 + "&profile=" + profile; //Construct post data.
                    String message;

                    try {
                        //Post the request to the server.
                        message = control.executePost(postData);
                    } catch (IOException error) {
                        message = error.toString();
                    }

                    if (message.charAt(0) == '1')
                    {
                        message = message.substring(1);
                        close();
                        //Registration succeeds and return back to login GUI and the new username is automatically
                        //displayed in the login GUI.
                        control.redirect("LoginSuccess");
                    }
                    else if (message.contains("Duplicate")) {
                        message = "The username already exists.";
                        //Convert the error generated by mysql into undertandable message.
                    }
                    JOptionPane.showMessageDialog(new JFrame(), message);
                    //Show a message to tell user the result.
                }
                else
                    JOptionPane.showMessageDialog(new JFrame(),
                    "The two typed password is not the same");
            }
    }
}





